stages:
- lint
- test
- push

flake8:
  stage: lint
  image: python:3.9-alpine
  before_script:
    - pip install -q flake8
  script:
    - flake8
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "production"'

format:
  stage: lint
  image: python:3.9-alpine
  before_script:
    - pip install black
  script:
    - echo "Linting with black"
    - black --check ./**/*.py
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "production"'

.docker-stage:
  image: docker:latest
  tags:
    - docker
  services:
    - docker:dind
  variables:
    IMAGE_NAME_BASE: $CI_REGISTRY_IMAGE/swiss-knife
    IMAGE_NAME: $IMAGE_NAME_BASE:$CI_COMMIT_SHORT_SHA
    DOCKER_TLS_CERTDIR: "/certs"

test:
  stage: test
  extends: .docker-stage
  before_script:
    - apk add --no-cache docker-compose
    - docker-compose -f compose.local.yml config
  script:
    - docker-compose -f compose.local.yml run swiss-knife pytest -vss
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "production"'

push:
  stage: push
  extends: .docker-stage
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --target python -f Dockerfile -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $IMAGE_NAME_BASE:$CI_COMMIT_BRANCH
    - docker push $IMAGE_NAME
    - docker push $IMAGE_NAME_BASE:$CI_COMMIT_BRANCH
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "production"'


