version: "3"

services:
  swiss-knife:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    image: swiss-knife-image
    container_name: swiss-knife
    volumes: 
      - .:/app
