# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9-alpine
    steps:
      - checkout
      - run: 
          name: Install dependencies 
          command: | 
            pip install black
            black --check ./**/*.py
      - test:
          name: Run docker-compose
          command: |
            apk add --no-cache docker-compose
            docker-compose -f compose.local.yml config
