# CircleCI configuration file
version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run: 
          name: Install dependencies 
          command: | 
            ls -al
            pwd
            pip install black
            black --check ./**/*.py
      - run: 
          name: Run docker-compose
          command: |
            apk add --no-cache docker docker-compose
            docker-compose -f compose.local.yml config
      - run: 
          name: Docker build
          command: |
            docker build --target python -f Dockerfile -t swiss-army-knife:0.1 .

workflows:
  on_commit:
    jobs:
      - build_and_test
