# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9-alpine
    steps:
      - checkout
      - run: 
          name: Install dependencies 
          command: pip install black

