# CircleCI configuration file
version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run: 
          name: Install dependencies 
          command: | 
            pyenv versions
            echo '3.9.13' > .python-version  
            pip install black
            black --check ./**/*.py
      - run: 
          name: Docker build
          command: |
            docker build --target python -f Dockerfile -t swiss-army-knife:0.1 .

workflows:
  on_commit:
    jobs:
      - build_and_test
